import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from "../../src/components/shared/NavBar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AgriMark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="agriMarket">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto max-w-7xl font-poppins`}
      >
        <NavBar />
        <main className="mt-10 mb-10 min-h-[calc(100vh-432px)]">
          {children}
        </main>
      </body>
    </html>
  );
}
